#!/usr/bin/env bash
#
# Author:   Bert Van Vreckem <bert.vanvreckem@gmail.com>
#
# Initialise an Ansible project, based on
# https://github.com/bertvv/ansible-skeleton/

set -u # abort on unbound variable

usage() {
cat << EOF
Usage: ${0##*/} [-h] [ROLE_NAME]

Create the Ansible role scaffolding

Options:
    -h          show this help message and exit
EOF
}

if [ "$#" -lt "1" ]; then
    usage
    exit 2
fi

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  usage
  exit 0
fi

project="$1"

if [ -d "${project}" ]; then
  echo "Project directory ${project} already exists. Bailing out." >&2
  exit 1
fi

shift

wget https://github.com/bertvv/ansible-skeleton/archive/master.zip
unzip master.zip
rm master.zip

mv ansible-skeleton-master "${project}"
git init "${project}"
cd "${project}" || exit
git add .
git commit --message "Initial commit"
