#!/usr/bin/env bash
#
# Author:   Bert Van Vreckem <bert.vanvreckem@gmail.com>
#
# Initialise an Ansible project, based on
# https://github.com/bertvv/ansible-skeleton/

set -u # abort on unbound variable

usage() {
cat << _EOF_
Usage: ${0} PROJECT_NAME [ROLE]...
  Initialises a new Ansible role project based on
  https://github.com/bertvv/ansible-skeleton
_EOF_
}

while getopts ":a" opt; do
  case $opt in
    a)
      echo "-a was triggered!" >&2
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

if [ "$#" -lt "1" ]; then
    echo "Expected at least 1 argument, got $#" >&2
    usage
    exit 2
fi

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  usage
  exit 0
fi

project="$1"

if [ -d "${project}" ]; then
  echo "Project directory ${project} already exists. Bailing out." >&2
  exit 1
fi

shift

wget https://github.com/bertvv/ansible-skeleton/archive/master.zip
unzip master.zip
rm master.zip

mv ansible-skeleton-master "${project}"
git init "${project}"
cd "${project}" || exit
git add .
git commit --message "Initial commit"
